### ISSUE TITLE
Can we add the Hacktoberfest tag to the repository?

### ISSUE THREAD

**Issue by mabasic** [tailwindcomponents/e-commerce#2]
https://hacktoberfest.digitalocean.com/resources/maintainers

If you complete the challenge you can choose to plant a tree in your name or you can get a tshirt.

There are two ways to participate: as a maintainer or as a contributor.

Maintainer has to add the tag `hacktoberfest` to the repo or apply tag `hacktoberfest-accepted` to the PR and merge 5 PRs.

Contributors have to submit 5 PRs which get merged in this month.

I've played for two years now and I have one tree planted and one t-shirt 👍

**Comment by khatabwedaa** [comment]
looks awesome I will take look at it soon, thanks again for the PR!

**Comment by mabasic** [comment]
Sure thing, but could you add the tag `hacktoberfest-accepted` to my PR so that I would get credited?

**Comment by khatabwedaa** [comment]
Done

**Comment by mabasic** [comment]
Thank you ❤
